version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  app-data:

services:
  redis:
    image: redis:7-alpine
    container_name: app_redis
    restart: unless-stopped
    ports:
      - "6382:6379"
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: database
    restart: unless-stopped
    tty: true
    volumes:
      - "./.docker/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking_app
    ports:
      - "5432:5432"
    networks:
      - app-network

  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./main:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  main:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    container_name: main
    restart: unless-stopped
    tty: true
    volumes:
      - ./main:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - postgres
      - webserver